
baseURL = "https://himanshunc.github.io/StudyNotes/"
languageCode = "en-us"
title = "AWS Study Notes"
theme = "github.com/adityatelange/hugo-PaperMod"

[params]
  ShowToc = true
  ShowBreadCrumbs = true
  ShowReadingTime = true
  env = "production"
  googleAnalytics = ""

[menu]
  [[menu.main]]
    name = "AWS VPC"
    url = "/aws/vpc/"
