
baseURL = "https://himanshunc.github.io/StudyNotes/"
languageCode = "en-us"
title = "AWS Study Notes"
theme = "github.com/adityatelange/hugo-PaperMod"

[params]
  ShowToc = true
  ShowBreadCrumbs = true
  ShowReadingTime = true
  env = "production"
  googleAnalytics = ""
  showFullWidthFirstPost = false
  customCSS = ["css/custom.css"]

[menu]
  [[menu.main]]
    name = "AWS"
    url = "/aws/vpc/"

  [[menu.main]]
    name = "DevOps"
    url = "/devops/"